pipeline {
  agent any

  environment {
    IMAGE_NAME = "sunaodisha/ecommerce-frontend"
    IMAGE_TAG  = "${BUILD_NUMBER}"
    GITOPS_REPO = "https://github.com/sunaofficial/ecommerce-gitops.git"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        sh """
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} src/frontend
        """
      }
    }

    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker-sant',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh """
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
          """
        }
      }
    }

    stage('Update GitOps Repo') {
  steps {
    withCredentials([usernamePassword(
      credentialsId: 'github-sant',
      usernameVariable: 'GIT_USER',
      passwordVariable: 'GIT_PASS'
    )]) {
      sh """
        rm -rf ecommerce-gitops

        git clone https://${GIT_USER}:${GIT_PASS}@github.com/sunaofficials/ecommerce-gitops.git
        cd ecommerce-gitops

        sed -i 's|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|' frontend/deployment.yaml
        git config --global user.email "santanu.nayak@harman.com"
        git config --global user.name "sunaofficilas"
        git add frontend/deployment.yaml
        git commit -m "Update frontend image to ${IMAGE_TAG}"
        git push
      """
    }
  }
}
}
}
